name: Deploy static content to Pages

on:
  push:
    branches:
      - main # O "master", según tu rama

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: . # Carpeta raíz

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
